### ISSUE TITLE
Out of bounds error during mesh creation

### ISSUE THREAD

**Issue by tischi** [mobie/arabidopsis-root-lm-project#3]
@constantinpape 

There are several segments that cause an error when the current code is trying to create a mesh.
I suspect that those segments that are cut off by the image boundary.

An example is: label 89 at time point 1

If you have any ideas, let me know. 

Anyway I will work on this more at some point (https://github.com/tischi/imagej-utils/issues/44)

**Comment by constantinpape** [comment]
Ok, I don't want to pull master in mobie-viewer right now because I have some experimental changes for reading private buckets, but I can check it out some time next week.
In the meantime, can you maybe post the error's trace back?

**Comment by tischi** [comment]
I was more thinking about whether you can see anything **"funny" in the input data**. The java error is pretty deep in the code and (for my taste) complicated imglib2 stuff, I don't think I would like to bother you with that ;-)

**Comment by constantinpape** [comment]
> I was more thinking about whether you can see anything **"funny" in the input data**. 

Ok, I will check it out once I update master. 

> The java error is pretty deep in the code and (for my taste) complicated imglib2 stuff, I don't think I would like to bother you with that ;-)

I became pretty good at reading obscure java tracebacks recently ;).

**Comment by constantinpape** [comment]
I tried running it with the current master, but ran into this issue: https://github.com/mobie/mobie-viewer-fiji/issues/216

**Comment by constantinpape** [comment]
Cannot check this due to https://github.com/mobie/mobie-viewer-fiji/issues/501.

**Comment by constantinpape** [comment]
Can confirm that the error still exists:
```
java.lang.ArrayIndexOutOfBoundsException: 262144
	at net.imglib2.img.basictypeaccess.array.AbstractIntArray.getValue(AbstractIntArray.java:61)
	at net.imglib2.type.numeric.integer.GenericIntType.getInt(GenericIntType.java:137)
	at net.imglib2.type.numeric.integer.UnsignedIntType.get(UnsignedIntType.java:180)
	at net.imglib2.type.numeric.integer.UnsignedIntType.getIntegerLong(UnsignedIntType.java:197)
	at net.imglib2.type.numeric.integer.AbstractIntegerType.getRealDouble(AbstractIntegerType.java:62)
	at de.embl.cba.tables.mesh.MeshExtractor.generateMesh(MeshExtractor.java:597)
	at org.embl.mobie.viewer.mesh.MeshCreator.createMesh(MeshCreator.java:74)
	at org.embl.mobie.viewer.mesh.MeshCreator.createCustomTriangleMesh(MeshCreator.java:106)
	at org.embl.mobie.viewer.mesh.MeshCreator.createSmoothCustomTriangleMesh(MeshCreator.java:95)
	at org.embl.mobie.viewer.volume.SegmentsVolumeViewer.updateSelectedSegments(SegmentsVolumeViewer.java:204)
	at org.embl.mobie.viewer.volume.SegmentsVolumeViewer.lambda$updateView$0(SegmentsVolumeViewer.java:172)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-91" java.lang.RuntimeException: Could not create mesh for segment 89.0 at time point 1
	at org.embl.mobie.viewer.mesh.MeshCreator.createCustomTriangleMesh(MeshCreator.java:116)
	at org.embl.mobie.viewer.mesh.MeshCreator.createSmoothCustomTriangleMesh(MeshCreator.java:95)
	at org.embl.mobie.viewer.volume.SegmentsVolumeViewer.updateSelectedSegments(SegmentsVolumeViewer.java:204)
	at org.embl.mobie.viewer.volume.SegmentsVolumeViewer.lambda$updateView$0(SegmentsVolumeViewer.java:172)
	at java.lang.Thread.run(Thread.java:748)
```
